# Generated by Django 5.1.4 on 2025-01-15 03:44

import django_summernote.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('stock', models.PositiveIntegerField()),
                ('detail', django_summernote.fields.SummernoteTextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
