# Generated by Django 5.1.4 on 2025-01-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('gm', 'gm'), ('pcs', 'pcs')], default='kg', max_length=3),
        ),
    ]
