# Generated by Django 5.1.4 on 2025-01-15 14:13

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
