# Generated by Django 5.1.4 on 2025-01-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_price_after_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_after_discount',
        ),
    ]
