# Generated by Django 5.1.4 on 2025-01-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('gm', 'gm'), ('pcs', 'pcs'), ('dozen', 'dozen')], default='kg', max_length=7),
        ),
    ]
