# Generated by Django 5.1.4 on 2025-01-17 13:06

import django.utils.timezone
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', django_summernote.fields.SummernoteTextField()),
                ('discount', models.PositiveIntegerField(help_text='in percentage')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
