# Generated by Django 5.1.4 on 2025-01-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
