# Generated by Django 5.1.4 on 2025-01-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
