# Generated by Django 5.1.4 on 2025-01-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_aboutus_email_aboutus_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'EMployee'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name_plural': 'Position'},
        ),
    ]
