# Generated by Django 5.1.4 on 2025-01-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_alter_aboutus_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee'},
        ),
    ]
