# Generated by Django 5.1.4 on 2025-01-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
