# Generated by Django 5.1.4 on 2025-01-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_aboutus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logo')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
