# Generated by Django 5.1.4 on 2025-01-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_ourpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpartner',
            name='logo',
            field=models.ImageField(blank=True, height_field='150px', null=True, upload_to='partner_logo', width_field='150px'),
        ),
    ]
