# Generated by Django 5.1.4 on 2025-01-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_alter_ourpartner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpartner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_logo'),
        ),
    ]
