# Generated by Django 5.1.4 on 2025-01-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0009_alter_ourpartner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images'),
        ),
    ]
