# Generated by Django 5.1.4 on 2025-01-17 17:36

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0010_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='policies',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
