# Generated by Django 5.1.4 on 2025-01-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
