# Generated by Django 5.1.4 on 2025-01-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('inner_charge', models.PositiveIntegerField()),
                ('outer_charge', models.PositiveIntegerField()),
            ],
        ),
    ]
