# Generated by Django 5.1.4 on 2025-01-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='ShipmentCharge',
        ),
    ]
