# Generated by Django 5.1.4 on 2025-01-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_delete_currency_delete_shipmentcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
