# Generated by Django 5.1.4 on 2025-01-16 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartitem_total_price'),
        ('product', '0010_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=500)),
                ('order_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packing', 'Packing'), ('On the way', 'On the way'), ('Placed', 'Placed')], default='Accepted', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('products', models.ManyToManyField(to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
