# Generated by Django 5.1.4 on 2025-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_confirmorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
