# Generated by Django 5.1.4 on 2025-01-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_confirmorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmorder',
            name='products',
            field=models.ManyToManyField(to='cart.cartitem'),
        ),
    ]
