# Generated by Django 5.1.4 on 2025-01-17 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cuopon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuopon',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
