# Generated by Django 5.1.4 on 2025-01-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_cuopon_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuopon',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
