# Generated by Django 5.1.4 on 2025-01-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cuopon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuopon',
            name='discount',
            field=models.PositiveIntegerField(help_text='in percentage'),
        ),
    ]
