# Generated by Django 5.1.4 on 2025-01-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_cuopon_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuopon',
            options={'ordering': ['is_active']},
        ),
    ]
