# Generated by Django 5.1.4 on 2025-01-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_cuopon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuopon',
            options={'ordering': ['-created_at']},
        ),
    ]
