# Generated by Django 5.1.4 on 2025-01-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_cuopon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='cuopon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cuopon'),
        ),
    ]
