# Generated by Django 5.1.4 on 2025-01-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_confirmorder_cuopon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuopon',
            new_name='Coupon',
        ),
        migrations.RenameField(
            model_name='confirmorder',
            old_name='cuopon',
            new_name='coupon',
        ),
    ]
