# Generated by Django 5.1.4 on 2025-01-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_rename_cuopon_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmorder',
            name='order_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packing', 'Packing'), ('On the way', 'On the way'), ('Placed', 'Placed'), ('Ccncled', 'Ccncled')], default='Accepted', max_length=12),
        ),
    ]
