# Generated by Django 5.1.4 on 2025-01-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_confirmorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='placed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
