# Generated by Django 5.1.4 on 2025-01-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_confirmorder_placed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
