# Generated by Django 5.1.4 on 2025-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_confirmorder_discount_price'),
        ('product', '0014_remove_product_discount_price_delete_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
