# Generated by Django 5.1.4 on 2025-01-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_coupon_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
    ]
